env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
#  env:
#    matrix:
#      - foo: 123
#        bar: abc
#      - foo: 789
#        baz: xyz
  freebsd_instance:
    matrix:
      - name: 13-CURRENT
        image_family: freebsd-13-0-snap
      - name: 12.1-STABLE
        image_family: freebsd-12-1-snap
      - name: 12.1-RELEASE
        image_family: freebsd-12-1
      - name: 11.3-STABLE
        image_family: freebsd-11-3-snap
      - name: 11.3-RELEASE
        image_family: freebsd-11-3
#    cpu: 8
#    memory: 24G
#  install_script:
#    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
#    - pkg upgrade -y
  script:
    - ./show.sh
