env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
#  env:
#    matrix:
#      - foo: 123
#        bar: abc
#      - foo: 789
#        baz: xyz
  freebsd_instance:
    matrix:
      image: freebsd-13-0-snap
      image: freebsd-12-1
      image: freebsd-12-1-snap
      image: freebsd-12-0
      image: freebsd-12-0-snap
      image: freebsd-11-3
      image: freebsd-11-3-snap
#    cpu: 8
#    memory: 24G
#  install_script:
#    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
#    - pkg upgrade -y
  script:
    - ./show.sh
