env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
#  env:
#    matrix:
#      - foo: 123
#        bar: abc
#      - foo: 789
#        baz: xyz
  freebsd_instance:
    cpu: 4
    memory: 8g
  matrix:
    - name: 14-CURRENT
      freebsd_instance:
        image_family: freebsd-14-0-snap
    - name: 13.0-RELEASE
      freebsd_instance:
        image_family: freebsd-13-0
    - name: 12.2-RELEASE
      freebsd_instance:
        image_family: freebsd-12-2
    - name: 11.4-RELEASE
      freebsd_instance:
        image_family: freebsd-11-4
  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - ASSUME_ALWAYS_YES=yes pkg bootstrap -f
#    - pkg upgrade -y
    - pkg install -y neofetch
  script:
    - ./show.sh
